import 'package:easy_localization/easy_localization.dart';
import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import '../../../../../config/language/locale_keys.g.dart';
import '../../../../../config/res/assets.gen.dart';
import '../../../../../config/res/config_imports.dart';
import '../../../../../core/base_crud/code/presentation/cubit/base_cubit/async_cubit.dart';
import '../../../../../core/extensions/base_state.dart';
import '../../../../../core/extensions/text_style_extensions.dart';
import '../../../../../core/extensions/widgets/sized_box_helper.dart';
import '../../../../../core/navigation/navigator.dart';
import '../../../../../core/network/api_endpoints.dart';
import '../../../../../core/network/network_request.dart';
import '../../../../../core/network/network_service.dart';
import '../../../../../core/widgets/dialogs/success_dialog.dart';
import '../../../../../core/widgets/custom_messages.dart';
import '../../../../../core/widgets/universal_media/widgets.dart';
import '../../../../../core/widgets/pickers/default_bottom_sheet.dart';

part '../../entity/team_player.dart';
part '../cubits/team_cubit.dart';
part '../view/team_tab_view.dart';
part '../widgets/team_header_widget.dart';
part '../widgets/team_member_card_widget.dart';
part '../widgets/team_request_card_widget.dart';
part '../widgets/team_segmented_tabs.dart';
