import 'dart:ui' as ui;

import 'package:easy_localization/easy_localization.dart';
import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter/services.dart';

import '../../../../../../../../config/language/locale_keys.g.dart';
import '../../../../../../../../config/res/config_imports.dart';
import '../../../../../../../../core/navigation/navigator.dart';
import '../../../../../../../../core/shared/cubits/user_cubit/user_cubit.dart';
import '../../../../../../../../core/shared/models/user_model.dart';
import '../../../../../../../../core/widgets/buttons/default_button.dart';
import '../../../../../../../../core/widgets/custom_appbar.dart';
import '../../../../../admin/admin_home/presentation/cubits/admin_order_details_cubit.dart';
import '../../../../../../../../core/shared/models/request_state.dart';
import '../../../../../../../../core/extensions/base_state.dart';
import '../../../../../../../../core/network/network_service.dart';
import '../../data/datasources/orders_remote_data_source.dart';
import '../../data/repositories/orders_repository_impl.dart';
import '../../domain/repositories/orders_repository.dart';
import '../../entity/order_model.dart';
import '../../entity/order_tabs.dart';

part '../cubits/orders_cubit.dart';
part '../cubits/orders_state.dart';
part '../view/admin_order_details_screen.dart';
part '../view/delivery_order_details_screen.dart';
part '../view/a5_invoice_screen.dart';
part '../view/orders_screen.dart';
part '../widgets/order_card.dart';
part '../widgets/admin_order_details_actions.dart';
part '../widgets/delivery_order_details_actions.dart';
part '../widgets/order_details_body.dart';
part '../widgets/order_details_row.dart';
part '../widgets/order_status_chip.dart';
part '../widgets/a5_invoice_card.dart';
part '../widgets/a5_invoice_row.dart';
part '../widgets/orders_body.dart';
part '../widgets/orders_tabs.dart';
