import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter_svg/svg.dart';
import '../../../../config/language/languages.dart';
import '../../../../config/language/locale_keys.g.dart';
import '../../../../config/res/config_imports.dart';
import '../../../../features/logic/home/presentation/imports/view_imports.dart';
import '../../../extensions/context_extension.dart';
import '../../../extensions/text_style_extensions.dart';
import '../../../navigation/navigator.dart';
import '../../buttons/default_button.dart';

part '../operations/intro_clipper.dart';
part '../operations/intro_edge_operation.dart';
part '../intro_carousel_widget.dart.dart';
part '../intro_component_widget.dart';
part '../intro_section_widget.dart';
part '../models/intro_dto.dart';
